# Generated by Django 5.2.15 on 2026-06-20 20:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='ℹ️ Ex.: Almoço de Quinta, Jantar diário.', max_length=100, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, help_text='ℹ️ Desmarque para desativar o cardápio inteiro.', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Cardápio',
                'verbose_name_plural': 'Cardápios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='ℹ️ Ex.: Proteínas, Bebidas, Sobremesas.', max_length=80, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('PROTEINA', 'Proteína'), ('ACOMPANHAMENTO', 'Acompanhamento'), ('GRELHADO', 'Grelhado'), ('ESPETINHO', 'Espetinho'), ('SANDUICHE', 'Sanduíche'), ('SOPA', 'Sopa'), ('BEBIDA', 'Bebida'), ('SOBREMESA', 'Sobremesa'), ('ADICIONAL', 'Adicional'), ('OUTRO', 'Outro')], help_text='ℹ️ Define o papel no bot (proteína e acompanhamento entram no prato; os demais são avulsos).', max_length=20, verbose_name='Tipo')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='ℹ️ Em que ordem aparece no cardápio (0 = primeiro).', verbose_name='Ordem de exibição')),
                ('ativa', models.BooleanField(default=True, help_text='ℹ️ Desmarque para esconder o grupo inteiro.', verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadeCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], help_text='ℹ️ Em que dia este cardápio fica ativo.', verbose_name='Dia da semana')),
                ('periodo', models.CharField(choices=[('ALMOCO', 'Almoço'), ('JANTAR', 'Jantar'), ('CUSTOM', 'Personalizado')], default='ALMOCO', help_text="ℹ️ Almoço (11–15h) ou Jantar (15–19h30). 'Personalizado' = defina o horário.", max_length=8, verbose_name='Período')),
                ('hora_inicio', models.TimeField(help_text='ℹ️ Preenchido sozinho no Almoço/Jantar.', verbose_name='De')),
                ('hora_fim', models.TimeField(help_text='ℹ️ Idem.', verbose_name='Até')),
                ('cardapio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='cardapio.cardapio', verbose_name='Cardápio')),
            ],
            options={
                'verbose_name': 'Horário do cardápio',
                'verbose_name_plural': 'Horários do cardápio',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='ℹ️ Nome que o cliente vê no WhatsApp. Ex.: Carne Assada.', max_length=120, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, help_text='ℹ️ Detalhes/ingredientes mostrados ao cliente quando ele seleciona o item (opcional).', verbose_name='Descrição')),
                ('modo_venda', models.CharField(choices=[('MONTAGEM', 'Montagem (por peso)'), ('FAIXA', 'Faixas de preço'), ('UNIDADE', 'Unidade (preço fixo)'), ('ADICIONAL', 'Adicional')], default='UNIDADE', help_text='ℹ️ Montagem = entra no prato por peso. Faixa = tamanhos com preços. Unidade = preço fixo. Adicional = extra (ex.: queijo).', max_length=12, verbose_name='Como é vendido')),
                ('preco', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='ℹ️ Só para itens vendidos por Unidade/Adicional. Deixe 0 para Montagem ou Faixa.', max_digits=8, verbose_name='Preço fixo (R$)')),
                ('preco_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="ℹ️ Opcional. Preço por quilo desta carne no modo 'só proteína' (ex.: 159,90). Deixe 0 para usar a tabela padrão da loja.", max_digits=8, verbose_name='Preço por kg — só proteína (R$)')),
                ('ativo', models.BooleanField(default=True, help_text='ℹ️ Desmarque para esconder o item do cardápio (ex.: saiu de linha).', verbose_name='Ativo')),
                ('esgotado', models.BooleanField(default=False, help_text='ℹ️ Marque quando acabar no meio do dia. O item some do cardápio na hora.', verbose_name='Esgotado hoje')),
                ('sempre_disponivel', models.BooleanField(default=False, help_text='ℹ️ Marque para itens fixos (carne assada, arroz…): aparecem sempre que a loja está aberta, sem precisar de cardápio. Itens que variam ficam em cardápios.', verbose_name='Sempre disponível')),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='ℹ️ Desconto em porcentagem. Ex.: 10 = 10%. Deixe 0 para sem promoção.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Desconto (%)')),
                ('promo_inicio', models.DateTimeField(blank=True, help_text='ℹ️ Opcional. Em branco = começa já.', null=True, verbose_name='Início da promoção')),
                ('promo_fim', models.DateTimeField(blank=True, help_text='ℹ️ Opcional. Em branco = sem término.', null=True, verbose_name='Fim da promoção')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria', models.ForeignKey(help_text='ℹ️ A qual grupo do cardápio o item pertence (Proteínas, Acompanhamentos, Bebidas…).', on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='cardapio.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['categoria__ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='FaixaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(help_text='ℹ️ Tamanho mostrado ao cliente. Ex.: 300g, 500ml.', max_length=30, verbose_name='Tamanho')),
                ('preco', models.DecimalField(decimal_places=2, help_text='ℹ️ Preço deste tamanho.', max_digits=8, verbose_name='Preço (R$)')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='ℹ️ Ordem de exibição (0 aparece primeiro).', verbose_name='Ordem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='cardapio.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Faixa de preço',
                'verbose_name_plural': 'Faixas de preço',
                'ordering': ['produto', 'ordem'],
            },
        ),
        migrations.AddField(
            model_name='cardapio',
            name='produtos',
            field=models.ManyToManyField(blank=True, help_text='ℹ️ Itens que aparecem quando este cardápio está no ar.', related_name='cardapios', to='cardapio.produto', verbose_name='Produtos'),
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cardapio.produto',),
        ),
    ]
