# Generated by Django 5.2.15 on 2026-06-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='data_fim',
            field=models.DateField(blank=True, help_text='ℹ️ Só para Especial. Último dia em que vale.', null=True, verbose_name='Válido até'),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='data_inicio',
            field=models.DateField(blank=True, help_text='ℹ️ Só para Especial. Primeiro dia em que vale.', null=True, verbose_name='Válido de'),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='exclusivo',
            field=models.BooleanField(default=False, help_text='ℹ️ Quando no ar, substitui os cardápios normais (mostra só ele + os itens fixos). Ideal para datas comemorativas.', verbose_name='Exclusivo'),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='tipo',
            field=models.CharField(choices=[('NORMAL', 'Normal (semanal)'), ('ESPECIAL', 'Especial (por data)')], default='NORMAL', help_text='ℹ️ Normal = repete por dia da semana. Especial = vale numa data (ex.: feriado).', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='nome',
            field=models.CharField(help_text='ℹ️ Ex.: Almoço de Quinta, Dia das Mães.', max_length=100, verbose_name='Nome'),
        ),
    ]
