# Generated by Django 5.2.15 on 2026-06-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_cardapio_data_fim_cardapio_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='esgotado',
            field=models.BooleanField(default=False, help_text='ℹ️ Marque quando acabar — o item some do cardápio na hora. Continua esgotado até você desmarcar.', verbose_name='Esgotado'),
        ),
    ]
