# Generated by Django 5.2.15 on 2026-06-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_alter_produto_esgotado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadecardapio',
            name='hora_fim',
            field=models.TimeField(blank=True, help_text='ℹ️ Deixe em branco no Almoço/Jantar (preenche sozinho).', null=True, verbose_name='Até'),
        ),
        migrations.AlterField(
            model_name='disponibilidadecardapio',
            name='hora_inicio',
            field=models.TimeField(blank=True, help_text="ℹ️ Deixe em branco no Almoço/Jantar (preenche sozinho). No 'Personalizado', informe o horário.", null=True, verbose_name='De'),
        ),
    ]
