# Generated by Django 5.2.15 on 2026-07-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0004_alter_disponibilidadecardapio_hora_fim_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocao',
            options={'ordering': ['ordem_promo'], 'verbose_name': 'Promoção', 'verbose_name_plural': 'Promoções'},
        ),
        migrations.AddField(
            model_name='produto',
            name='ordem_promo',
            field=models.PositiveIntegerField(default=0, help_text='ℹ️ Ordem de exibição na lista de promoções (arraste no painel).', verbose_name='Ordem na Promoção'),
        ),
    ]
