# Generated by Django 5.2.15 on 2026-07-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0005_alter_promocao_options_produto_ordem_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='horario_fim',
            field=models.TimeField(blank=True, help_text='ℹ️ Opcional. Se preenchido, este produto só aparece até este horário.', null=True, verbose_name='Disponível até as'),
        ),
        migrations.AddField(
            model_name='produto',
            name='horario_inicio',
            field=models.TimeField(blank=True, help_text='ℹ️ Opcional. Se preenchido, este produto só aparece a partir deste horário, mesmo se o cardápio estiver ativo.', null=True, verbose_name='Disponível a partir das'),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='produtos',
            field=models.ManyToManyField(blank=True, help_text='ℹ️ Itens que aparecem quando este cardápio está no ar. ⚠️ DICA: Evite produtos com nomes maiores que 24 letras, pois o WhatsApp cortará o texto.', related_name='cardapios', to='cardapio.produto', verbose_name='Produtos'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(help_text="⚠️ Nome que o cliente vê. Limite ideal: 24 letras. Passando disso, o WhatsApp corta com '...'", max_length=120, verbose_name='Nome'),
        ),
    ]
