# Generated by Django 5.2.15 on 2026-08-17 21:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0006_produto_horario_fim_produto_horario_inicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoComplemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='ℹ️ Ex.: Escolha o tamanho, Adicionais, Ponto da carne.', max_length=80, verbose_name='Nome do grupo')),
                ('obrigatorio', models.BooleanField(default=False, help_text='ℹ️ Se marcado, o cliente é obrigado a escolher neste grupo.', verbose_name='Obrigatório')),
                ('min_escolhas', models.PositiveSmallIntegerField(default=0, help_text='ℹ️ Quantidade mínima que o cliente precisa escolher (0 = livre).', verbose_name='Mínimo de escolhas')),
                ('max_escolhas', models.PositiveSmallIntegerField(default=1, help_text='ℹ️ Quantidade máxima que o cliente pode escolher (0 = sem limite).', verbose_name='Máximo de escolhas')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='ℹ️ Ordem de exibição (0 aparece primeiro).', verbose_name='Ordem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_complemento', to='cardapio.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Grupo de complementos',
                'verbose_name_plural': 'Grupos de complementos',
                'ordering': ['produto', 'ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpcaoComplemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='ℹ️ Ex.: Bacon, Queijo extra, 500ml, Bem passado.', max_length=80, verbose_name='Nome')),
                ('preco_adicional', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='ℹ️ Quanto soma ao preço do item. 0 = sem custo extra.', max_digits=8, verbose_name='Preço adicional (R$)')),
                ('ativo', models.BooleanField(default=True, help_text='ℹ️ Desmarque para esconder a opção sem apagar.', verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='ℹ️ Ordem de exibição (0 aparece primeiro).', verbose_name='Ordem')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='cardapio.grupocomplemento', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Opção de complemento',
                'verbose_name_plural': 'Opções de complemento',
                'ordering': ['grupo', 'ordem', 'id'],
            },
        ),
    ]
