# Generated by Django 5.2.15 on 2026-09-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0007_grupocomplemento_opcaocomplemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='esgotado_em',
            field=models.DateField(blank=True, editable=False, help_text='Dia em que foi marcado como esgotado. Preenchido sozinho; serve para o item voltar ao cardápio na virada do dia.', null=True, verbose_name='Esgotado em'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='esgotado',
            field=models.BooleanField(default=False, help_text="ℹ️ Marque quando acabar — o item some do cardápio na hora e volta sozinho no dia seguinte. Para tirar de vez, desmarque 'Ativo'.", verbose_name='Esgotado'),
        ),
    ]
