# Generated by Django 5.2.15 on 2026-09-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0008_produto_esgotado_em_alter_produto_esgotado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('PROTEINA', 'Proteína'), ('ACOMPANHAMENTO', 'Acompanhamento'), ('GRELHADO', 'Grelhado'), ('ESPETINHO', 'Espetinho'), ('SANDUICHE', 'Sanduíche'), ('SOPA', 'Sopa'), ('BEBIDA', 'Bebida'), ('SOBREMESA', 'Sobremesa'), ('ADICIONAL', 'Adicional'), ('QUENTINHA', 'Quentinha (lojista)'), ('OUTRO', 'Outro')], help_text='ℹ️ Define o papel no bot (proteína e acompanhamento entram no prato; os demais são avulsos).', max_length=20, verbose_name='Tipo'),
        ),
    ]
