# Generated by Django 5.2.15 on 2026-09-30 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0009_alter_categoria_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='vinculado_a',
            field=models.ForeignKey(blank=True, help_text='ℹ️ Para item feito do mesmo ingrediente que outro (ex.: a quentinha de Frango Ensopado usa o mesmo frango da proteína). Quando o item de origem acaba, este some junto — a cozinha marca num lugar só.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivados', to='cardapio.produto', verbose_name='Segue a disponibilidade de'),
        ),
    ]
