# Generated by Django 5.2.15 on 2026-06-20 20:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(help_text='ℹ️ Bairro atendido. O bot só aceita pedidos dos bairros cadastrados aqui.', max_length=120, verbose_name='Bairro')),
                ('cep_inicio', models.CharField(blank=True, help_text='ℹ️ Opcional. Início da faixa de CEP atendida. Ex.: 22790-000.', max_length=9, verbose_name='CEP inicial')),
                ('cep_fim', models.CharField(blank=True, help_text='ℹ️ Opcional. Fim da faixa. Ex.: 22799-999.', max_length=9, verbose_name='CEP final')),
                ('ativo', models.BooleanField(default=True, help_text='ℹ️ Desmarque para parar de atender este bairro.', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Área de entrega',
                'verbose_name_plural': 'Áreas de entrega',
                'ordering': ['bairro'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(help_text='Identificador único no WhatsApp (E.164, ex.: 5521999998888).', max_length=20, unique=True, verbose_name='Telefone (WhatsApp)')),
                ('nome_whatsapp', models.CharField(blank=True, max_length=120, verbose_name='Nome no WhatsApp')),
                ('asaas_cliente_id', models.CharField(blank=True, db_index=True, help_text='Reutilizado para não recriar o cliente a cada cobrança.', max_length=60, verbose_name='ID do cliente (Asaas)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.CharField(default='Big Kilo', max_length=120, verbose_name='Nome da loja')),
                ('slogan', models.CharField(default='Comida Caseira', max_length=160, verbose_name='Slogan')),
                ('mensagem_abertura', models.TextField(default='Olá! Que bom que você entrou em contato com o Big Kilo 🍽️\nAtendemos a região do Novo Leblon e arredores.', help_text='ℹ️ Primeira mensagem que o cliente recebe ao chamar no WhatsApp.', verbose_name='Mensagem de boas-vindas')),
                ('area_atendimento_texto', models.CharField(default='Novo Leblon e arredores (Barra da Tijuca)', help_text='ℹ️ Frase curta sobre onde vocês entregam. Aparece logo no início da conversa.', max_length=200, verbose_name='Área de atendimento (resumo)')),
                ('completa_300', models.DecimalField(decimal_places=2, default=Decimal('31.97'), max_digits=8, verbose_name='Completa 300g')),
                ('completa_500', models.DecimalField(decimal_places=2, default=Decimal('50.95'), max_digits=8, verbose_name='Completa 500g')),
                ('completa_700', models.DecimalField(decimal_places=2, default=Decimal('69.93'), max_digits=8, verbose_name='Completa 700g')),
                ('lim_acomp_300', models.PositiveSmallIntegerField(default=2, verbose_name='Máx. acomp. 300g')),
                ('lim_acomp_500', models.PositiveSmallIntegerField(default=3, verbose_name='Máx. acomp. 500g')),
                ('lim_acomp_700', models.PositiveSmallIntegerField(default=4, verbose_name='Máx. acomp. 700g')),
                ('lim_prot_300', models.PositiveSmallIntegerField(default=1, verbose_name='Máx. proteína 300g')),
                ('lim_prot_500', models.PositiveSmallIntegerField(default=1, verbose_name='Máx. proteína 500g')),
                ('lim_prot_700', models.PositiveSmallIntegerField(default=2, verbose_name='Máx. proteína 700g')),
                ('proteina_300', models.DecimalField(decimal_places=2, default=Decimal('42.47'), max_digits=8, verbose_name='Só proteína 300g')),
                ('proteina_500', models.DecimalField(decimal_places=2, default=Decimal('68.45'), max_digits=8, verbose_name='Só proteína 500g')),
                ('proteina_700', models.DecimalField(decimal_places=2, default=Decimal('94.43'), max_digits=8, verbose_name='Só proteína 700g')),
                ('proteina_1000', models.DecimalField(decimal_places=2, default=Decimal('133.40'), max_digits=8, verbose_name='Só proteína 1kg')),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Paga diretamente ao entregador. Apenas informada ao cliente.', max_digits=8, verbose_name='Taxa de entrega (informativa)')),
                ('chave_pix', models.CharField(blank=True, help_text='ℹ️ Sua chave Pix (usada na cobrança quando integrar o Asaas).', max_length=140, verbose_name='Chave Pix')),
                ('hora_abertura', models.TimeField(default='11:00', help_text='ℹ️ Fora do horário o bot avisa que está fechado.', verbose_name='Abre às')),
                ('hora_fechamento', models.TimeField(default='20:00', verbose_name='Fecha às')),
                ('dias_funcionamento', models.JSONField(blank=True, default=list, help_text='Lista de dias (0=Seg ... 6=Dom). Vazio = todos os dias.', verbose_name='Dias de funcionamento')),
                ('aberto_forcado', models.BooleanField(default=False, help_text='Use em casos excepcionais para aceitar pedidos fora do horário.', verbose_name='Forçar aberto (ignora horário)')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração da loja',
                'verbose_name_plural': 'Configuração da loja',
            },
        ),
        migrations.CreateModel(
            name='SessaoBot',
            fields=[
                ('telefone', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Telefone')),
                ('estado_atual', models.CharField(choices=[('MENU_PRINCIPAL', 'Menu principal'), ('PEDINDO_ENDERECO', 'Pedindo endereço (bairro)'), ('PEDINDO_RUA', 'Pedindo endereço (rua)'), ('ESCOLHENDO_PESO', 'Escolhendo peso'), ('ESCOLHENDO_ITENS', 'Escolhendo proteína'), ('MONTANDO_PRATO', 'Montando prato'), ('ESCOLHENDO_FIXO', 'Escolhendo item'), ('ESCOLHENDO_FAIXA', 'Escolhendo tamanho'), ('NO_CARRINHO', 'No carrinho'), ('FINALIZANDO', 'Finalizando'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento')], default='MENU_PRINCIPAL', max_length=30, verbose_name='Estado atual')),
                ('carrinho_json', models.JSONField(blank=True, default=dict, verbose_name='Carrinho (JSON)')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Conversa (WhatsApp)',
                'verbose_name_plural': 'Conversas (WhatsApp)',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('COMPLETA', 'Refeição completa'), ('PROTEINA', 'Só proteína'), ('FIXO', 'Item avulso (preço fixo)')], default='FIXO', max_length=10, verbose_name='Modo')),
                ('peso_g', models.PositiveIntegerField(blank=True, help_text='Para pratos por peso (300/500/700/1000g).', null=True, verbose_name='Peso (g)')),
                ('variacao', models.CharField(blank=True, help_text='Faixa/tamanho escolhido (ex.: 500ml, Pão Brioche).', max_length=40, verbose_name='Variação')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Congelado no momento do pedido (proteína/base, sem adicionais).', max_digits=8, verbose_name='Preço unitário')),
                ('observacoes', models.CharField(blank=True, help_text='Ex.: sem cebola, bem passado.', max_length=200, verbose_name='Observações')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='cardapio.produto', verbose_name='Produto / Proteína')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
        migrations.CreateModel(
            name='ItemAcompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_adicional', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Adicional')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_como_acompanhamento', to='cardapio.produto', verbose_name='Acompanhamento')),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to='pedidos.itempedido', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Acompanhamento',
                'verbose_name_plural': 'Acompanhamentos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('PREPARANDO', 'Preparando'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], db_index=True, default='AGUARDANDO_PAGAMENTO', max_length=30, verbose_name='Status')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor total')),
                ('endereco_entrega', models.TextField(blank=True, verbose_name='Endereço de entrega')),
                ('bairro', models.CharField(blank=True, max_length=120, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Paga ao entregador na entrega (não incluída no Pix).', max_digits=8, verbose_name='Taxa de entrega')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações gerais')),
                ('asaas_cobranca_id', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='ID da cobrança (Asaas)')),
                ('asaas_pix_copia_cola', models.TextField(blank=True, verbose_name='Pix Copia e Cola')),
                ('comanda_impressa', models.BooleanField(default=False, verbose_name='Comanda impressa')),
                ('impressa_em', models.DateTimeField(blank=True, null=True, verbose_name='Impressa em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidos.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido', verbose_name='Pedido'),
        ),
    ]
