# Generated by Django 5.2.15 on 2026-06-23 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_alter_produto_esgotado'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(choices=[('BOAS_VINDAS', 'Boas-vindas / saudação'), ('AREA_ATENDIMENTO', 'Área de atendimento (resumo)'), ('PEDIR_BAIRRO', 'Pedir bairro'), ('FORA_AREA', 'Fora da área de entrega'), ('PEDIR_RUA', 'Pedir rua/endereço'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('PAGAMENTO_CONFIRMADO', 'Pagamento confirmado'), ('ANUNCIO_PROMO', 'Anúncio de promoção')], max_length=30, unique=True, verbose_name='Etapa')),
                ('texto', models.TextField(help_text='ℹ️ Use {bairro} onde fizer sentido. Emojis são bem-vindos.', verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Mensagem do bot',
                'verbose_name_plural': 'Mensagens do bot',
                'ordering': ['chave'],
            },
        ),
        migrations.CreateModel(
            name='PromocaoExclusiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desconto_percentual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Desconto (%)')),
                ('mensagem', models.CharField(blank=True, help_text="ℹ️ Texto que o bot mostra no início para este contato. Ex.: 'Pra você: 20% no pudim! 🍮'", max_length=200, verbose_name='Mensagem de anúncio')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes', to='pedidos.cliente', verbose_name='Cliente')),
                ('produto', models.ForeignKey(help_text='ℹ️ Funciona com itens de preço fixo (bebida, sanduíche, etc.).', on_delete=django.db.models.deletion.CASCADE, related_name='promocoes_exclusivas', to='cardapio.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Promoção exclusiva',
                'verbose_name_plural': 'Promoções exclusivas',
            },
        ),
        migrations.CreateModel(
            name='MensagemCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(choices=[('BOAS_VINDAS', 'Boas-vindas / saudação'), ('AREA_ATENDIMENTO', 'Área de atendimento (resumo)'), ('PEDIR_BAIRRO', 'Pedir bairro'), ('FORA_AREA', 'Fora da área de entrega'), ('PEDIR_RUA', 'Pedir rua/endereço'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('PAGAMENTO_CONFIRMADO', 'Pagamento confirmado'), ('ANUNCIO_PROMO', 'Anúncio de promoção')], max_length=30, verbose_name='Etapa')),
                ('texto', models.TextField(verbose_name='Texto personalizado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='pedidos.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Mensagem personalizada',
                'verbose_name_plural': 'Mensagens personalizadas',
                'unique_together': {('cliente', 'chave')},
            },
        ),
    ]
