# Generated by Django 5.2.15 on 2026-06-24 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_mensagembot_promocaoexclusiva_mensagemcliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemFluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(choices=[('BOAS_VINDAS', 'Boas-vindas / saudação'), ('AREA_ATENDIMENTO', 'Área de atendimento (resumo)'), ('PEDIR_BAIRRO', 'Pedir bairro'), ('FORA_AREA', 'Fora da área de entrega'), ('PEDIR_RUA', 'Pedir rua/endereço'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('PAGAMENTO_CONFIRMADO', 'Pagamento confirmado'), ('ANUNCIO_PROMO', 'Anúncio de promoção')], max_length=30, verbose_name='Etapa')),
                ('texto', models.TextField(verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Mensagem do fluxo',
                'verbose_name_plural': 'Mensagens do fluxo',
            },
        ),
        migrations.CreateModel(
            name='PerfilFluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='ℹ️ Ex.: Padrão, Natal, Tom descontraído.', max_length=100, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=False, help_text='ℹ️ Só um perfil fica ativo por vez.', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Fluxo de mensagens',
                'verbose_name_plural': 'Fluxos de mensagem',
                'ordering': ['-ativo', 'nome'],
            },
        ),
        migrations.DeleteModel(
            name='MensagemBot',
        ),
        migrations.AddField(
            model_name='mensagemfluxo',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='pedidos.perfilfluxo', verbose_name='Perfil'),
        ),
        migrations.AlterUniqueTogether(
            name='mensagemfluxo',
            unique_together={('perfil', 'chave')},
        ),
    ]
