# Generated by Django 5.2.15 on 2026-06-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_mensagemfluxo_perfilfluxo_delete_mensagembot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(db_index=True, max_length=20, verbose_name='Telefone')),
                ('direcao', models.CharField(choices=[('IN', 'Cliente'), ('OUT', 'Bot')], max_length=3, verbose_name='De quem')),
                ('texto', models.TextField(verbose_name='Mensagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Quando')),
            ],
            options={
                'verbose_name': 'Mensagem da conversa',
                'verbose_name_plural': 'Mensagens da conversa',
                'ordering': ['criado_em'],
            },
        ),
    ]
