# Generated by Django 5.2.15 on 2026-07-03 01:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_logmensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_agendada',
            field=models.DateField(blank=True, help_text='Preenchido quando é uma encomenda para outro dia.', null=True, verbose_name='Agendada para'),
        ),
        migrations.AlterField(
            model_name='configuracaoloja',
            name='chave_pix',
            field=models.CharField(blank=True, help_text='ℹ️ Opcional — só para sua referência. O Pix do cliente é gerado automaticamente pelo Asaas.', max_length=140, verbose_name='Chave Pix (referência)'),
        ),
        migrations.AlterField(
            model_name='configuracaoloja',
            name='taxa_entrega',
            field=models.DecimalField(decimal_places=2, default=Decimal('7.00'), help_text='Uma por pedido. Mostrada ao cliente no fechamento; paga ao entregador na entrega (não entra no Pix).', max_digits=8, verbose_name='Taxa de entrega'),
        ),
        migrations.AlterField(
            model_name='mensagemcliente',
            name='chave',
            field=models.CharField(choices=[('BOAS_VINDAS', 'Boas-vindas / saudação'), ('AREA_ATENDIMENTO', 'Área de atendimento (resumo)'), ('PEDIR_BAIRRO', 'Pedir bairro'), ('FORA_AREA', 'Fora da área de entrega'), ('PEDIR_RUA', 'Pedir rua/endereço'), ('PEDIR_CEP', 'Pedir CEP'), ('CEP_INVALIDO', 'CEP fora da área'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('PAGAMENTO_CONFIRMADO', 'Pagamento confirmado'), ('ANUNCIO_PROMO', 'Anúncio de promoção'), ('PEDIR_ENDERECO_COMPLETO', 'Pedir endereço completo (fechamento)'), ('ENCOMENDA_EM_BREVE', 'Encomenda futura (em breve)'), ('MONTAR_REFEICAO', 'Início montagem refeição'), ('ESCOLHER_PROTEINA', 'Escolher proteína'), ('ESCOLHER_ACOMPANHAMENTOS', 'Escolher acompanhamentos'), ('PEDIR_MAIS', 'Pedir mais itens?')], max_length=30, verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='mensagemfluxo',
            name='chave',
            field=models.CharField(choices=[('BOAS_VINDAS', 'Boas-vindas / saudação'), ('AREA_ATENDIMENTO', 'Área de atendimento (resumo)'), ('PEDIR_BAIRRO', 'Pedir bairro'), ('FORA_AREA', 'Fora da área de entrega'), ('PEDIR_RUA', 'Pedir rua/endereço'), ('PEDIR_CEP', 'Pedir CEP'), ('CEP_INVALIDO', 'CEP fora da área'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('PAGAMENTO_CONFIRMADO', 'Pagamento confirmado'), ('ANUNCIO_PROMO', 'Anúncio de promoção'), ('PEDIR_ENDERECO_COMPLETO', 'Pedir endereço completo (fechamento)'), ('ENCOMENDA_EM_BREVE', 'Encomenda futura (em breve)'), ('MONTAR_REFEICAO', 'Início montagem refeição'), ('ESCOLHER_PROTEINA', 'Escolher proteína'), ('ESCOLHER_ACOMPANHAMENTOS', 'Escolher acompanhamentos'), ('PEDIR_MAIS', 'Pedir mais itens?')], max_length=30, verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='sessaobot',
            name='estado_atual',
            field=models.CharField(choices=[('MENU_PRINCIPAL', 'Menu principal'), ('PEDINDO_ENDERECO', 'Pedindo endereço (bairro)'), ('PEDINDO_RUA', 'Pedindo endereço (rua)'), ('PEDINDO_CEP', 'Pedindo CEP'), ('ESCOLHENDO_PESO', 'Escolhendo peso'), ('ESCOLHENDO_ITENS', 'Escolhendo proteína'), ('MONTANDO_PRATO', 'Montando prato'), ('ESCOLHENDO_FIXO', 'Escolhendo item'), ('ESCOLHENDO_FAIXA', 'Escolhendo tamanho'), ('NO_CARRINHO', 'No carrinho'), ('FINALIZANDO', 'Finalizando'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('CONFIRMANDO_ITEM', 'Confirmando item montado'), ('OFERTA_BEBIDA', 'Oferta bebida/sobremesa'), ('PERGUNTANDO_MAIS_ITEM', 'Pedir mais itens?'), ('PEDINDO_ENDERECO_COMPLETO', 'Pedindo endereço completo'), ('ENCOMENDA_FUTURA', 'Encomenda futura')], default='MENU_PRINCIPAL', max_length=30, verbose_name='Estado atual'),
        ),
    ]
