# Generated by Django 5.2.15 on 2026-07-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_data_agendada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemcliente',
            name='chave',
            field=models.CharField(choices=[('BOAS_VINDAS', 'Boas-vindas / saudação'), ('AREA_ATENDIMENTO', 'Área de atendimento (resumo)'), ('PEDIR_BAIRRO', 'Pedir bairro'), ('FORA_AREA', 'Fora da área de entrega'), ('PEDIR_RUA', 'Pedir rua/endereço'), ('PEDIR_CEP', 'Pedir CEP'), ('CEP_INVALIDO', 'CEP fora da área'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('PAGAMENTO_CONFIRMADO', 'Pagamento confirmado'), ('ANUNCIO_PROMO', 'Anúncio de promoção'), ('PEDIR_ENDERECO_COMPLETO', 'Pedir endereço completo (fechamento)'), ('ENCOMENDA_EM_BREVE', 'Encomenda futura (em breve)'), ('MONTAR_REFEICAO', 'Início montagem refeição'), ('ESCOLHER_PROTEINA', 'Escolher proteína'), ('ESCOLHER_ACOMPANHAMENTOS', 'Escolher acompanhamentos'), ('PEDIR_MAIS', 'Pedir mais itens?'), ('RESUMO_CARRINHO', 'Resumo do carrinho'), ('PERGUNTAR_ADICIONAR', 'O que adicionar?'), ('PEDIR_DATA_ENCOMENDA', 'Pedir data da encomenda'), ('ENCOMENDA_AGENDADA', 'Encomenda agendada'), ('DATA_INVALIDA', 'Data inválida')], max_length=30, verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='mensagemfluxo',
            name='chave',
            field=models.CharField(choices=[('BOAS_VINDAS', 'Boas-vindas / saudação'), ('AREA_ATENDIMENTO', 'Área de atendimento (resumo)'), ('PEDIR_BAIRRO', 'Pedir bairro'), ('FORA_AREA', 'Fora da área de entrega'), ('PEDIR_RUA', 'Pedir rua/endereço'), ('PEDIR_CEP', 'Pedir CEP'), ('CEP_INVALIDO', 'CEP fora da área'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('PAGAMENTO_CONFIRMADO', 'Pagamento confirmado'), ('ANUNCIO_PROMO', 'Anúncio de promoção'), ('PEDIR_ENDERECO_COMPLETO', 'Pedir endereço completo (fechamento)'), ('ENCOMENDA_EM_BREVE', 'Encomenda futura (em breve)'), ('MONTAR_REFEICAO', 'Início montagem refeição'), ('ESCOLHER_PROTEINA', 'Escolher proteína'), ('ESCOLHER_ACOMPANHAMENTOS', 'Escolher acompanhamentos'), ('PEDIR_MAIS', 'Pedir mais itens?'), ('RESUMO_CARRINHO', 'Resumo do carrinho'), ('PERGUNTAR_ADICIONAR', 'O que adicionar?'), ('PEDIR_DATA_ENCOMENDA', 'Pedir data da encomenda'), ('ENCOMENDA_AGENDADA', 'Encomenda agendada'), ('DATA_INVALIDA', 'Data inválida')], max_length=30, verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='sessaobot',
            name='estado_atual',
            field=models.CharField(choices=[('MENU_PRINCIPAL', 'Menu principal'), ('PEDINDO_ENDERECO', 'Pedindo endereço (bairro)'), ('PEDINDO_RUA', 'Pedindo endereço (rua)'), ('PEDINDO_CEP', 'Pedindo CEP'), ('ESCOLHENDO_PESO', 'Escolhendo peso'), ('ESCOLHENDO_ITENS', 'Escolhendo proteína'), ('MONTANDO_PRATO', 'Montando prato'), ('ESCOLHENDO_FIXO', 'Escolhendo item'), ('ESCOLHENDO_FAIXA', 'Escolhendo tamanho'), ('NO_CARRINHO', 'No carrinho'), ('FINALIZANDO', 'Finalizando'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('CONFIRMANDO_ITEM', 'Confirmando item montado'), ('OFERTA_BEBIDA', 'Escolhendo bebida/sobremesa extra'), ('PERGUNTANDO_MAIS_ITEM', 'Pedir mais itens? (legado)'), ('RESUMO_CARRINHO', 'Resumo do carrinho'), ('PERGUNTANDO_ADICIONAR', 'O que adicionar?'), ('PEDINDO_ENDERECO_COMPLETO', 'Pedindo endereço completo'), ('ENCOMENDA_FUTURA', 'Encomenda futura')], default='MENU_PRINCIPAL', max_length=30, verbose_name='Estado atual'),
        ),
    ]
