# Generated by Django 5.2.15 on 2026-07-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_mensagemcliente_chave_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaoloja',
            name='aberto_forcado',
        ),
    ]
