# Generated by Django 5.2.15 on 2026-07-14 13:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_remove_configuracaoloja_aberto_forcado'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='completa_1000',
            field=models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=8, verbose_name='Completa 1kg'),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='guarnicao_1000',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=8, verbose_name='Só guarnição 1kg'),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='guarnicao_700',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=8, verbose_name='Só guarnição 700g'),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='lim_acomp_1000',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Máx. acomp. 1kg'),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='lim_prot_1000',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Máx. proteína 1kg'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='modo',
            field=models.CharField(choices=[('COMPLETA', 'Refeição completa'), ('PROTEINA', 'Só proteína'), ('GUARNICAO', 'Só guarnição'), ('FIXO', 'Item avulso (preço fixo)')], default='FIXO', max_length=10, verbose_name='Modo'),
        ),
    ]
