# Generated by Django 5.2.15 on 2026-07-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_alter_mensagemcliente_chave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='hora_agendada',
            field=models.TimeField(blank=True, help_text='Preenchido com o horário solicitado pelo cliente.', null=True, verbose_name='Horário da encomenda'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('ENTREGA', 'Entrega em domicílio'), ('RETIRADA', 'Retirada na loja')], default='ENTREGA', max_length=20, verbose_name='Como vai receber'),
        ),
        migrations.AlterField(
            model_name='sessaobot',
            name='estado_atual',
            field=models.CharField(choices=[('MENU_PRINCIPAL', 'Menu principal'), ('PEDINDO_ENDERECO', 'Pedindo endereço (bairro)'), ('PEDINDO_RUA', 'Pedindo endereço (rua)'), ('PEDINDO_CEP', 'Pedindo CEP'), ('ESCOLHENDO_PESO', 'Escolhendo peso'), ('ESCOLHENDO_ITENS', 'Escolhendo proteína'), ('ESCOLHENDO_TIPO_GRANDE_PORCAO', 'Escolhendo tipo G.P.'), ('MONTANDO_PRATO', 'Montando prato'), ('ESCOLHENDO_FIXO', 'Escolhendo item'), ('ESCOLHENDO_FAIXA', 'Escolhendo tamanho'), ('NO_CARRINHO', 'No carrinho'), ('FINALIZANDO', 'Finalizando'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('CONFIRMANDO_ITEM', 'Confirmando item montado'), ('OFERTA_BEBIDA', 'Escolhendo bebida/sobremesa extra'), ('PERGUNTANDO_MAIS_ITEM', 'Pedir mais itens? (legado)'), ('RESUMO_CARRINHO', 'Resumo do carrinho'), ('PERGUNTANDO_ADICIONAR', 'O que adicionar?'), ('PEDINDO_ENDERECO_COMPLETO', 'Pedindo endereço completo'), ('ENCOMENDA_FUTURA', 'Encomenda futura (Data)'), ('ENCOMENDA_HORARIO', 'Encomenda futura (Horário)'), ('ESCOLHENDO_TIPO_ENTREGA', 'Escolhendo Entrega/Retirada')], default='MENU_PRINCIPAL', max_length=30, verbose_name='Estado atual'),
        ),
    ]
