# Generated by Django 5.2.15 on 2026-08-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_alter_pedido_status_alter_sessaobot_estado_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='imprimir_ao_fechar',
            field=models.BooleanField(default=True, help_text='ℹ️ Imprime a comanda assim que o cliente fecha o pedido (a cozinha já começa), sem esperar a confirmação do pagamento. Desligue para imprimir só depois de confirmar o Pix no painel.', verbose_name='Imprimir ao fechar o pedido'),
        ),
        migrations.AlterField(
            model_name='configuracaoloja',
            name='chave_pix',
            field=models.CharField(blank=True, help_text="ℹ️ Sua chave Pix REAL. É ela que gera o 'copia e cola' com o valor do pedido para o cliente pagar.", max_length=140, verbose_name='Chave Pix'),
        ),
    ]
