# Generated by Django 5.2.15 on 2026-09-11 14:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_configuracaoloja_imprimir_ao_fechar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='exigir_pagamento',
            field=models.BooleanField(default=True, help_text='ℹ️ Desligue para o cliente fechar o pedido SEM Pix (a comanda imprime na hora e o pagamento é combinado na loja). Útil para testar a impressão.', verbose_name='Exigir pagamento pelo bot'),
        ),
        migrations.AlterField(
            model_name='configuracaoloja',
            name='taxa_entrega',
            field=models.DecimalField(decimal_places=2, default=Decimal('7.00'), help_text='Uma por pedido. Entra no Pix do cliente; o restaurante repassa ao entregador.', max_digits=8, verbose_name='Taxa de entrega'),
        ),
        migrations.AlterField(
            model_name='mensagemcliente',
            name='chave',
            field=models.CharField(choices=[('BOAS_VINDAS', 'Boas-vindas / saudação'), ('AREA_ATENDIMENTO', 'Área de atendimento (resumo)'), ('PEDIR_BAIRRO', 'Pedir bairro'), ('FORA_AREA', 'Fora da área de entrega'), ('PEDIR_RUA', 'Pedir rua/endereço'), ('PEDIR_CEP', 'Pedir CEP'), ('CEP_INVALIDO', 'CEP fora da área'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('PAGAMENTO_CONFIRMADO', 'Pagamento confirmado'), ('ANUNCIO_PROMO', 'Anúncio de promoção'), ('PEDIR_ENDERECO_COMPLETO', 'Pedir endereço completo (fechamento)'), ('ENCOMENDA_EM_BREVE', 'Encomenda futura (em breve)'), ('MONTAR_REFEICAO', 'Início montagem refeição'), ('ESCOLHER_PROTEINA', 'Escolher proteína'), ('ESCOLHER_ACOMPANHAMENTOS', 'Escolher acompanhamentos'), ('PEDIR_MAIS', 'Pedir mais itens?'), ('RESUMO_CARRINHO', 'Resumo do carrinho'), ('PERGUNTAR_ADICIONAR', 'O que adicionar?'), ('PEDIR_DATA_ENCOMENDA', 'Pedir data da encomenda'), ('ENCOMENDA_AGENDADA', 'Encomenda agendada'), ('ENCOMENDA_CONTATO', 'Encomenda — entraremos em contato'), ('DATA_INVALIDA', 'Data inválida'), ('BTN_MENU_REFEICAO', 'Menu: Montar refeição'), ('BTN_MENU_REFEICAO_ENC', 'Menu: Montar refeição (Encomenda)'), ('BTN_MENU_GRANDES', 'Menu: Grandes porções'), ('BTN_MENU_GRANDES_ENC', 'Menu: Grandes porções (Encomenda)'), ('BTN_MENU_ENCOMENDA', 'Menu: Encomenda outro dia'), ('BTN_MENU_SANDUICHES', 'Menu: Sanduíches'), ('BTN_MENU_SOPAS', 'Menu: Sopas'), ('BTN_TIPO_PROTEINA', 'Botão: Grande porção de Proteína'), ('BTN_TIPO_GUARNICAO', 'Botão: Grande porção de Guarnição'), ('BTN_ADD_OUTRA_GRANDE', 'Botão: Outra grande porção'), ('DESC_ADD_OUTRA_GRANDE', 'Desc: Outra grande porção'), ('BTN_ADD_REFEICAO', 'Botão: Nova refeição'), ('DESC_ADD_REFEICAO', 'Desc: Nova refeição'), ('BTN_ADD_BEBIDA', 'Botão: Bebida'), ('DESC_ADD_BEBIDA', 'Desc: Bebida'), ('BTN_ADD_SOBREMESA', 'Botão: Sobremesa'), ('DESC_ADD_SOBREMESA', 'Desc: Sobremesa'), ('BTN_ADD_FECHAR', 'Botão: Finalizar pedido'), ('DESC_ADD_FECHAR', 'Desc: Finalizar pedido'), ('BTN_CARRINHO_ADICIONAR', 'Botão: Carrinho Adicionar'), ('BTN_CARRINHO_FECHAR', 'Botão: Carrinho Fechar'), ('BTN_CONFIRMAR_SIM', 'Botão: Confirmar Sim'), ('BTN_CONFIRMAR_CORRIGIR', 'Botão: Confirmar Corrigir')], max_length=30, verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='mensagemfluxo',
            name='chave',
            field=models.CharField(choices=[('BOAS_VINDAS', 'Boas-vindas / saudação'), ('AREA_ATENDIMENTO', 'Área de atendimento (resumo)'), ('PEDIR_BAIRRO', 'Pedir bairro'), ('FORA_AREA', 'Fora da área de entrega'), ('PEDIR_RUA', 'Pedir rua/endereço'), ('PEDIR_CEP', 'Pedir CEP'), ('CEP_INVALIDO', 'CEP fora da área'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('PAGAMENTO_CONFIRMADO', 'Pagamento confirmado'), ('ANUNCIO_PROMO', 'Anúncio de promoção'), ('PEDIR_ENDERECO_COMPLETO', 'Pedir endereço completo (fechamento)'), ('ENCOMENDA_EM_BREVE', 'Encomenda futura (em breve)'), ('MONTAR_REFEICAO', 'Início montagem refeição'), ('ESCOLHER_PROTEINA', 'Escolher proteína'), ('ESCOLHER_ACOMPANHAMENTOS', 'Escolher acompanhamentos'), ('PEDIR_MAIS', 'Pedir mais itens?'), ('RESUMO_CARRINHO', 'Resumo do carrinho'), ('PERGUNTAR_ADICIONAR', 'O que adicionar?'), ('PEDIR_DATA_ENCOMENDA', 'Pedir data da encomenda'), ('ENCOMENDA_AGENDADA', 'Encomenda agendada'), ('ENCOMENDA_CONTATO', 'Encomenda — entraremos em contato'), ('DATA_INVALIDA', 'Data inválida'), ('BTN_MENU_REFEICAO', 'Menu: Montar refeição'), ('BTN_MENU_REFEICAO_ENC', 'Menu: Montar refeição (Encomenda)'), ('BTN_MENU_GRANDES', 'Menu: Grandes porções'), ('BTN_MENU_GRANDES_ENC', 'Menu: Grandes porções (Encomenda)'), ('BTN_MENU_ENCOMENDA', 'Menu: Encomenda outro dia'), ('BTN_MENU_SANDUICHES', 'Menu: Sanduíches'), ('BTN_MENU_SOPAS', 'Menu: Sopas'), ('BTN_TIPO_PROTEINA', 'Botão: Grande porção de Proteína'), ('BTN_TIPO_GUARNICAO', 'Botão: Grande porção de Guarnição'), ('BTN_ADD_OUTRA_GRANDE', 'Botão: Outra grande porção'), ('DESC_ADD_OUTRA_GRANDE', 'Desc: Outra grande porção'), ('BTN_ADD_REFEICAO', 'Botão: Nova refeição'), ('DESC_ADD_REFEICAO', 'Desc: Nova refeição'), ('BTN_ADD_BEBIDA', 'Botão: Bebida'), ('DESC_ADD_BEBIDA', 'Desc: Bebida'), ('BTN_ADD_SOBREMESA', 'Botão: Sobremesa'), ('DESC_ADD_SOBREMESA', 'Desc: Sobremesa'), ('BTN_ADD_FECHAR', 'Botão: Finalizar pedido'), ('DESC_ADD_FECHAR', 'Desc: Finalizar pedido'), ('BTN_CARRINHO_ADICIONAR', 'Botão: Carrinho Adicionar'), ('BTN_CARRINHO_FECHAR', 'Botão: Carrinho Fechar'), ('BTN_CONFIRMAR_SIM', 'Botão: Confirmar Sim'), ('BTN_CONFIRMAR_CORRIGIR', 'Botão: Confirmar Corrigir')], max_length=30, verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='taxa_entrega',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Somada ao Pix do cliente. O restaurante repassa ao entregador.', max_digits=8, verbose_name='Taxa de entrega'),
        ),
    ]
