# Generated by Django 5.2.15 on 2026-09-11 14:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_exigir_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='guarnicao_500',
            field=models.DecimalField(decimal_places=2, default=Decimal('46.90'), max_digits=8, verbose_name='Só guarnição 500g'),
        ),
    ]
