# Generated by Django 5.2.15 on 2026-09-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_corrigindo_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('PIX', 'Pix (antes de preparar)'), ('CARTAO', 'Cartão na entrega')], default='PIX', help_text='Cartão = o pedido já vai para a cozinha e a maquininha vai junto na entrega.', max_length=10, verbose_name='Forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='sessaobot',
            name='estado_atual',
            field=models.CharField(choices=[('ATENDIMENTO_HUMANO', 'Atendimento Humano (Pausado)'), ('MENU_PRINCIPAL', 'Menu principal'), ('PEDINDO_ENDERECO', 'Pedindo endereço (bairro)'), ('PEDINDO_RUA', 'Pedindo endereço (rua)'), ('PEDINDO_CEP', 'Pedindo CEP'), ('ESCOLHENDO_PESO', 'Escolhendo peso'), ('ESCOLHENDO_ITENS', 'Escolhendo proteína'), ('ESCOLHENDO_TIPO_GRANDE_PORCAO', 'Escolhendo tipo G.P.'), ('MONTANDO_PRATO', 'Montando prato'), ('ESCOLHENDO_FIXO', 'Escolhendo item'), ('ESCOLHENDO_FAIXA', 'Escolhendo tamanho'), ('NO_CARRINHO', 'No carrinho'), ('FINALIZANDO', 'Finalizando'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('CONFIRMANDO_ITEM', 'Confirmando item montado'), ('OFERTA_BEBIDA', 'Escolhendo bebida/sobremesa extra'), ('PERGUNTANDO_MAIS_ITEM', 'Pedir mais itens? (legado)'), ('RESUMO_CARRINHO', 'Resumo do carrinho'), ('CORRIGINDO_PEDIDO', 'Corrigindo o pedido'), ('ESCOLHENDO_PAGAMENTO', 'Escolhendo forma de pagamento'), ('PERGUNTANDO_ADICIONAR', 'O que adicionar?'), ('PEDINDO_ENDERECO_COMPLETO', 'Pedindo endereço completo'), ('ENCOMENDA_FUTURA', 'Encomenda futura (Data)'), ('ENCOMENDA_HORARIO', 'Encomenda futura (Horário)'), ('TIPO_ENTREGA_INICIAL', 'Escolhendo Entrega/Retirada Inicial'), ('ESCOLHENDO_TIPO_ENTREGA', 'Escolhendo Entrega/Retirada')], default='MENU_PRINCIPAL', max_length=30, verbose_name='Estado atual'),
        ),
    ]
