# Generated by Django 5.2.15 on 2026-09-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0018_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pago_em',
            field=models.DateTimeField(blank=True, help_text='Preenchido quando o pagamento e confirmado. Vazio = ainda nao pago.', null=True, verbose_name='Pago em'),
        ),
    ]
