# Generated by Django 5.2.15 on 2026-09-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0019_pago_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='bot_pausado',
            field=models.BooleanField(default=False, help_text='ℹ️ Liga o aviso de pausa: quem mandar mensagem recebe só o texto abaixo e o bot não atende pedidos. Use para feriado, férias ou manutenção.', verbose_name='Pausar o bot'),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='mensagem_pausa',
            field=models.TextField(default='Olá! 🍽️\nNo momento os pedidos pelo WhatsApp estão pausados.\n\nVoltamos a atender *a partir de segunda-feira*. Até já! 😊', help_text='ℹ️ Mensagem enviada a quem chamar enquanto o bot estiver pausado.', verbose_name='Aviso enquanto pausado'),
        ),
    ]
