# Generated by Django 5.2.15 on 2026-09-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0020_bot_pausado'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='email_encomendas',
            field=models.EmailField(blank=True, default='ltratch@yahoo.com.br', help_text='ℹ️ Recebe um aviso sempre que alguém pedir encomenda pelo bot, com link para responder o cliente no WhatsApp.', max_length=254, verbose_name='E-mail para avisos de encomenda'),
        ),
    ]
