# Generated by Django 5.2.15 on 2026-09-22 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0021_email_encomendas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando contato'), ('EM_CONTATO', 'Em negociação'), ('FECHADA', 'Fechada'), ('PERDIDA', 'Perdida')], db_index=True, default='AGUARDANDO', max_length=12, verbose_name='Situação')),
                ('observacoes', models.TextField(blank=True, help_text='ℹ️ O que o cliente pediu, data combinada, valores — anote aqui.', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Pedida em')),
                ('atendido_em', models.DateTimeField(blank=True, null=True, verbose_name='Atendida em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomendas', to='pedidos.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Encomenda',
                'verbose_name_plural': 'Encomendas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
