# Generated by Django 5.2.15 on 2026-09-22 18:37

import secrets

from django.db import migrations, models


def gerar_token(apps, schema_editor):
    """Já nasce com link para a loja não precisar salvar a configuração à toa."""
    Cfg = apps.get_model("pedidos", "ConfiguracaoLoja")
    for cfg in Cfg.objects.filter(token_cozinha=""):
        cfg.token_cozinha = secrets.token_urlsafe(24)
        cfg.save(update_fields=["token_cozinha"])


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0022_encomenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='token_cozinha',
            field=models.CharField(blank=True, editable=False, help_text='Chave secreta do link que a cozinha salva na tela inicial do celular. Apague este campo para gerar um novo e derrubar o antigo.', max_length=40, verbose_name='Link do Modo Cozinha'),
        ),
        migrations.RunPython(gerar_token, migrations.RunPython.noop),
    ]
