# Generated by Django 5.2.15 on 2026-09-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0023_configuracaoloja_token_cozinha'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='link_ifood',
            field=models.URLField(blank=True, help_text='ℹ️ Cole o link da loja no iFood. Com o delivery fechado, quem mandar mensagem recebe este link para pedir por lá. Deixe vazio para só avisar que está fechado.', max_length=300, verbose_name='Link do iFood'),
        ),
    ]
