# Generated by Django 5.2.15 on 2026-09-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0024_configuracaoloja_link_ifood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoloja',
            name='mensagem_pausa',
            field=models.TextField(default='Olá! 🍽️\nNo momento não estamos aceitando pedidos pelo WhatsApp.\n\nVolte mais tarde ou peça por outro canal. Até já! 😊', help_text='ℹ️ Mensagem enviada a quem chamar enquanto o bot estiver pausado.', verbose_name='Aviso enquanto pausado'),
        ),
    ]
