# Generated by Django 5.2.15 on 2026-09-28 13:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0025_alter_configuracaoloja_mensagem_pausa'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoLojista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='ℹ️ Como aparece para o lojista. O WhatsApp corta em 24 letras.', max_length=24, verbose_name='Nome')),
                ('endereco', models.CharField(blank=True, help_text='ℹ️ Aparece embaixo do nome, como referência. Até 72 letras.', max_length=72, verbose_name='Endereço')),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=Decimal('2.90'), help_text='ℹ️ Frete cobrado dos lojistas deste ponto.', max_digits=8, verbose_name='Taxa de entrega')),
                ('ativo', models.BooleanField(default=True, help_text='ℹ️ Desmarque para parar de atender sem apagar.', verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='ℹ️ 0 aparece primeiro.', verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Ponto de entrega (lojista)',
                'verbose_name_plural': 'Pontos de entrega (lojista)',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='canal',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('LOJISTA', 'Lojista (shopping)')], db_index=True, default='CLIENTE', max_length=10, verbose_name='Canal'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='loja_lojista',
            field=models.CharField(blank=True, help_text='Nome/número da loja dentro do shopping, para o entregador achar.', max_length=120, verbose_name='Loja'),
        ),
        migrations.AlterField(
            model_name='sessaobot',
            name='estado_atual',
            field=models.CharField(choices=[('ATENDIMENTO_HUMANO', 'Atendimento Humano (Pausado)'), ('MENU_PRINCIPAL', 'Menu principal'), ('PEDINDO_ENDERECO', 'Pedindo endereço (bairro)'), ('PEDINDO_RUA', 'Pedindo endereço (rua)'), ('PEDINDO_CEP', 'Pedindo CEP'), ('ESCOLHENDO_PESO', 'Escolhendo peso'), ('ESCOLHENDO_ITENS', 'Escolhendo proteína'), ('ESCOLHENDO_TIPO_GRANDE_PORCAO', 'Escolhendo tipo G.P.'), ('MONTANDO_PRATO', 'Montando prato'), ('ESCOLHENDO_FIXO', 'Escolhendo item'), ('ESCOLHENDO_FAIXA', 'Escolhendo tamanho'), ('NO_CARRINHO', 'No carrinho'), ('FINALIZANDO', 'Finalizando'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('CONFIRMANDO_ITEM', 'Confirmando item montado'), ('OFERTA_BEBIDA', 'Escolhendo bebida/sobremesa extra'), ('PERGUNTANDO_MAIS_ITEM', 'Pedir mais itens? (legado)'), ('RESUMO_CARRINHO', 'Resumo do carrinho'), ('CORRIGINDO_PEDIDO', 'Corrigindo o pedido'), ('ESCOLHENDO_PAGAMENTO', 'Escolhendo forma de pagamento'), ('PERGUNTANDO_ADICIONAR', 'O que adicionar?'), ('PEDINDO_ENDERECO_COMPLETO', 'Pedindo endereço completo'), ('ENCOMENDA_FUTURA', 'Encomenda futura (Data)'), ('ENCOMENDA_HORARIO', 'Encomenda futura (Horário)'), ('TIPO_ENTREGA_INICIAL', 'Escolhendo Entrega/Retirada Inicial'), ('ESCOLHENDO_PUBLICO', 'Cliente ou lojista?'), ('ESCOLHENDO_PONTO', 'Lojista: em qual shopping?'), ('PEDINDO_LOJA', 'Lojista: qual loja?'), ('LOJISTA_MENU', 'Lojista: menu'), ('LOJISTA_PROTEINA', 'Lojista: escolhendo proteína'), ('LOJISTA_SALADA', 'Lojista: escolhendo salada'), ('SANDUICHE_SALADA', 'Sanduíche: com salada?'), ('ESCOLHENDO_TIPO_ENTREGA', 'Escolhendo Entrega/Retirada')], default='MENU_PRINCIPAL', max_length=30, verbose_name='Estado atual'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ponto_lojista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidos.pontolojista', verbose_name='Shopping'),
        ),
    ]
