# Generated by Django 5.2.15 on 2026-09-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0026_pontolojista_pedido_canal_pedido_loja_lojista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='pausado_lojista',
            field=models.BooleanField(default=False, help_text='ℹ️ Lojistas dos shoppings recebem só o aviso abaixo. Os clientes continuam sendo atendidos.', verbose_name='Fechar delivery para lojistas'),
        ),
        migrations.AlterField(
            model_name='configuracaoloja',
            name='bot_pausado',
            field=models.BooleanField(default=False, help_text='ℹ️ Clientes que mandarem mensagem recebem só o aviso abaixo, sem conseguir pedir. Os lojistas continuam sendo atendidos.', verbose_name='Fechar delivery para clientes'),
        ),
    ]
