# Generated by Django 5.2.15 on 2026-09-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0010_produto_vinculado_a'),
        ('pedidos', '0027_configuracaoloja_pausado_lojista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='quentinha_inclui',
            field=models.CharField(default='arroz, feijão, farofa e salada', help_text='ℹ️ O que acompanha a proteína. Aparece na tela do lojista.', max_length=120, verbose_name='A quentinha vem com'),
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='quentinha_saladas',
            field=models.ManyToManyField(blank=True, help_text='ℹ️ As saladas que o lojista escolhe. Use os acompanhamentos que já existem no cardápio: assim, salada marcada como esgotada some daqui também.', related_name='quentinhas_salada', to='cardapio.produto', verbose_name='Saladas da quentinha'),
        ),
    ]
