# Generated by Django 5.2.15 on 2026-07-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefone_whatsapp',
            field=models.CharField(blank=True, help_text='Número do WhatsApp conectado ao bot (ex: 5521999999999)', max_length=20, null=True),
        ),
    ]
